version: '3'
services:
  backend:
    image: rapidpro:5.2.6-alpine
    build:
      context: rapidpro
      args:
        - RAPIDPRO_VERSION=v5.2.6
    depends_on:
      - mailroom
      - redis
      - postgresql
    env_file:
      - rapidpro.env
      - secrets
    environment:
      - MAILROOM_URL=http://mailroom:8090
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/15
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
  celery_base:
    image: rapidpro:5.2.6-alpine
    depends_on:
      - backend
    env_file:
      - secrets
    environment:
      - BOXTYPE=celery-base
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/15
      - DJANGO_DEBUG=off
      - LOG_LEVEL=ERROR
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
  celery_msgs:
    image: rapidpro:5.2.6-alpine
    depends_on:
      - backend
    env_file:
      - secrets
    environment:
      - BOXTYPE=celery-msgs
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/15
      - DJANGO_DEBUG=off
      - LOG_LEVEL=ERROR
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
  redis:
    image: redis:alpine
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
  postgresql:
    image: mdillon/postgis:10-alpine
    volumes:
      - /var/lib/postgresql/10/:/var/lib/postgresql:Z
    environment:
      - POSTGRES_DB=rapidpro
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
  archiver:
    image: praekeltfoundation/rp-indexer:2
    environment:
      - ARCHIVER_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - ARCHIVER_DELETE=true
    volumes:
      - "/tmp:/tmp:Z"
  mailroom:
   image: praekeltfoundation/mailroom:5.2.4
   environment:
     - MAILROOM_ADDRESS=0.0.0.0
     - MAILROOM_DOMAIN=mailroom
     - MAILROOM_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
     - MAILROOM_REDIS=redis://redis:6379/15
   ports:
     - "8090:8080"
  courier:
   image: praekeltfoundation/courier:5.2.0
   ports:
     - "8080:8080"
   depends_on:
     - backend
     - postgresql
   logging:
      driver: journald
      options:
        tag: "{{.Name}}"
   environment:
     - COURIER_DOMAIN=courier
     - COURIER_SPOOL_DIR=/tmp
     - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
     - COURIER_REDIS=redis://redis:6379/15
  rapidpro:
    build:
      context: nginx
      args:
        CERT_ORG_NAME: kiboko.io
        CERT_ORG_UNIT: kiboko.io
        CERT_COMMON_NAME: rapidpro
        CERT_COUNTRY: KE
        CERT_LOCALITY: KE
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - courier
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4443:4443"
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
